let strip = neopixel.create(DigitalPin.P5, 18, NeoPixelMode.RGB)
strip.clear()
k_Bit.LED_brightness(70)
basic.forever(function () {
    k_Bit.SetLed(255, 0, 0)
    basic.pause(1000)
    k_Bit.SetLed(0, 255, 0)
    basic.pause(1000)
    k_Bit.SetLed(0, 0, 255)
    basic.pause(1000)
    k_Bit.SetLed(0, 255, 255)
    basic.pause(1000)
    k_Bit.SetLed(255, 0, 255)
    basic.pause(1000)
    k_Bit.SetLed(255, 255, 0)
    basic.pause(1000)
    k_Bit.SetLed(255, 255, 255)
    basic.pause(1000)
})
basic.forever(function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(1000)
})
